### ISSUE TITLE
AttributeError: 'StandardRoIHeadOAMIL' object has no attribute '_epoch'

### ISSUE THREAD

**Issue by Gaodzlearn** [cxliu0/OA-MIL#8]
The following code throws an error：
(https://github.com/cxliu0/OA-MIL/blob/bc72311e06115bb193cad8d9b7d6d8ad5927ea72/mmdet/models/roi_heads/standard_roi_head_oamil.py#L247)
AttributeError: 'StandardRoIHeadOAMIL' object has no attribute '_epoch'
I checked the code didn't find the  defination of "self._epoch". I think the 'self._epoch' attribute should be get from 'runner', so I kindly ask for an explanation.

**Comment by cxliu0** [comment]
This error may occur if you use a pre-installed mmcv instead of the one in this repository, because we have modified mmcv to assign ``_epoch`` to the detection model during training. 
 
Therefore, we recommend installing mmcv following the procedure in README (as follows). This shall resolve the error.
```
# install mmcv (will take a while to process)
cd mmcv
MMCV_WITH_OPS=1 pip install -e . 
```

**Comment by Gaodzlearn** [comment]
> This error may occur if you use a pre-installed mmcv instead of the one in this repository, because we have modified mmcv to assign `_epoch` to the detection model during training.
> 
> Therefore, we recommend installing mmcv following the procedure in README (as follows). This shall resolve the error.
> 
> ```
> # install mmcv (will take a while to process)
> cd mmcv
> MMCV_WITH_OPS=1 pip install -e . 
> ```

Problem solved. Thank you very much!
